### ISSUE TITLE
installing isicle 

### ISSUE THREAD

**Issue by samuelcajahuaringa** [pnnl/isicle#16]
Hello ISICLE developers,
I try to install ISICLE inside a python venv but I have de following problem to installing the requirements:

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
Installing collected packages: toposort, throttler, stopit, pytz, pulp, plac, openbabel, fastjsonschema, connection-pool, appdirs, wrapt, urllib3, tzdata, traitlets, tabulate, smmap, smart-open, six, rpds-py, reretry, pyyaml, psutil, platformdirs, Pillow, packaging, numpy, MarkupSafe, joblib, idna, humanfriendly, dpath, docutils, datrie, configargparse, charset-normalizer, certifi, attrs, yte, scipy, requests, referencing, rdkit, python-dateutil, patsy, jupyter-core, jinja2, gitdb, pandas, jsonschema-specifications, gitpython, statsmodels, jsonschema, nbformat, snakemake
  Running setup.py install for openbabel ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for openbabel did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      running install
      /home/samuel/Documents/CCS_database/isicle/isicle_venv/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build_ext
      Warning: invalid version number '3.1.1.1'.
      Guessing Open Babel location:
      - include_dirs: ['/home/samuel/Documents/CCS_database/isicle/isicle_venv/include', '/usr/include/python3.10', '/usr/local/include/openbabel3']
      - library_dirs: ['/usr/local/lib']
      building 'openbabel._openbabel' extension
      swigging openbabel/openbabel-python.i to openbabel/openbabel-python_wrap.cpp
      swig -python -c++ -small -O -templatereduce -naturalvar -I/home/samuel/Documents/CCS_database/isicle/isicle_venv/include -I/usr/include/python3.10 -I/usr/local/include/openbabel3 -o openbabel/openbabel-python_wrap.cpp openbabel/openbabel-python.i
      
      Error: SWIG failed. Is Open Babel installed?
      You may need to manually specify the location of Open Babel include and library directories. For example:
        python setup.py build_ext -I/usr/local/include/openbabel3 -L/usr/local/lib
        python setup.py install
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> openbabel

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
can help me to install the ISICLE please.

Thanks

**Comment by smcolby** [comment]
Please try the instructions on Read the Docs: https://isicle.readthedocs.io/en/latest/getting_started/installation.html

**Comment by samuelcajahuaringa** [comment]
Thank a lot @smcolby , after successfully installing: 
"
Installing collected packages: isicle
  Running setup.py develop for isicle
Successfully installed isicle-2.0.0"

I run the example collision_cross_section.py
the code finished with follow message:
"
-------------------
Overall wall time  : 0h : 0m :55s

 CREST terminated normally.
"
but not finished all calculations until to obtain the CCS, and When I try the example of read the docs and have the follow problems: with the function "isicle.io.load", and not is possible continue the calculations, is possible send a example similar to the file collision_cross_section.py to test the new version of ISICLE.

Thanks a lot,
Samuel

**Comment by smcolby** [comment]
Apologies for the delay, this dropped off my radar. You can use `isicle.load` instead of `isicle.io.load`, which should resolve the issue. The docs have unfortunately not been updated to reflect this yet.
